#!/usr/bin/env bash
# Full local check on a Unix host: format, lint, generated contract, tests,
# release build, web build. The macOS counterpart of scripts/check.ps1; both
# run the same steps in the same order so a green run means the same thing on
# either development platform.
#
# Usage: scripts/check.sh [--skip-web] [--skip-release]
set -euo pipefail

skip_web=0
skip_release=0
for arg in "$@"; do
    case "$arg" in
        --skip-web) skip_web=1 ;;
        --skip-release) skip_release=1 ;;
        -h|--help)
            sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "unknown option: $arg" >&2
            exit 2
            ;;
    esac
done

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

# rustup's shims are not always on a non-interactive PATH.
if ! command -v cargo >/dev/null 2>&1; then
    for candidate in "$HOME/.cargo/bin" "$(rustup show home 2>/dev/null)/toolchains/$(rustup show active-toolchain 2>/dev/null | cut -d' ' -f1)/bin"; do
        if [ -x "$candidate/cargo" ]; then
            PATH="$candidate:$PATH"
            export PATH
            break
        fi
    done
fi
command -v cargo >/dev/null 2>&1 || { echo "cargo not found on PATH" >&2; exit 1; }

step() {
    printf '\033[36m==> %s\033[0m\n' "$1"
    shift
    "$@"
}

step "cargo fmt --check" cargo fmt --check
step "cargo clippy" cargo clippy --all-targets -- -D warnings

# The contract is generated by a test; a stale checked-in copy is a failure,
# not something to regenerate silently.
step "generated API contract" cargo test -p eidos-service export_api_contract --lib
if ! git diff --quiet -- web/src/generated/api.ts; then
    echo "generated API contract was stale; commit web/src/generated/api.ts" >&2
    exit 1
fi

step "cargo test" cargo test

if [ "$skip_release" -eq 0 ]; then
    step "cargo build --release" cargo build --release
fi

if [ "$skip_web" -eq 0 ]; then
    command -v npm >/dev/null 2>&1 || { echo "npm not found on PATH" >&2; exit 1; }
    cd web
    [ -d node_modules ] || step "npm ci" npm ci
    step "npm run lint" npm run lint
    step "npm test" npm test
    step "npm run build" npm run build
    cd "$root"
fi

printf '\033[32mAll checks passed.\033[0m\n'
